name: 'Bitrise Feature Builder'
description: 'Trigger feature builds on bitrise by commenting on a PR'
author: 'Sixt'
inputs:
  github-token:
    description: 'Token for GitHub. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  bitrise-token:
    description: 'Token for Bitrise. Should be configured as secret in the repo and then passed using {{ secrets.BITRISE_TOKEN }}'
    required: true
  bitrise-slug:
    description: 'The slug of the application on Bitrise. You can find the slug by opening the Bitrise dashboard and copying the alphanumeric characters in the URL: https://app.bitrise.io/app/<all_slug>'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: "message-square"
  color: "orange"
